Fix TermNodes returning null when not array and fix type being set to generic TermNode in Taxonomy field
wp-graphql/wpgraphql-acf pull request #85
Opened 2023-09-06 11:14 UTC by cristobalbahe

What does this implement/fix? Explain your changes.
---------------------------------------------------
Taxonomy field was returning null when field_type was set to return a single value (with select or radio button). By not returning null in case it is not an array (which is the default return when these field types are selected), it properly returns the term.
![Before](https://i.ibb.co/7Wk67Cf/before-0.png)

Also the type was being set to generic TermNode type, which did not allow to query custom fields inside these fields. By setting the type correctly to the taxonomy name it works properly
![Before](https://i.ibb.co/8PptkrB/before-1.png)

After changing these everything works as expected
![Before](https://i.ibb.co/pwT6q45/after.png)

Does this close any currently open issues?
------------------------------------------

Any relevant logs, error output, GraphiQL screenshots, etc?
-------------------------------------
(If it’s long, please paste to https://ghostbin.com/ and insert the link here.)

Any other comments?
-------------------
…

Where has this been tested?
---------------------------
**Operating System:** …

**WordPress Version:** …

2023-09-06 19:03 UTC, jasonbahl requested changes
I think the logic in the resolver to handle the array vs non-array is good. 

The logic re: the $type should be removed from this PR. 

I'd like to re-visit giving folks the ability to override the Type that the field will return, but that should probably happen independently of this PR.

2023-09-07 07:09 UTC, cristobalbahe commented on src/FieldType/Taxonomy.php
>  						'toType'  => 'TermNode',
Hi Jason!
I must have uploaded the wrong code (sorry, not the tidiest github user 😅). 
Indeed, my intention was to set ```toType``` to ```$type``` in order to be able to access the type specific fields (i.e custom fields for category) which does not appear on termNode. 
Anyway, silly of me I just realized i can query a union like so and I can still get the category specific fields, which woudl not cause a change to the Schema:
``` graphql
{
...
#this is a [TermNode] list
  nodes { 
    name
    ... on Category {
      categoryFields {
        color
      }
    }
  }
...
}
```
so I removed the $type change and leave only the array vs non-array logic. 
Thank you!

2023-09-07 14:24 UTC, jasonbahl commented on src/FieldType/Taxonomy.php
> +							if ( ! empty( $value ) && is_array( $value ) ) {
```suggestion
							if ( is_array( $value ) ) {
```

2023-09-07 14:24 UTC, jasonbahl commented on src/FieldType/Taxonomy.php
> +							if ( empty( $value )) {
```suggestion
							if ( empty( $value ) ) {
```

2023-09-11 19:51 UTC, merged